from time import sleep

take_input = input("Which company you want to hack? ")

print(f"Getting into {take_input}'s Database........")
sleep(5)
print(f"Getting password info of {take_input}....")
sleep(6)
print(f"Got the passwords, Trying to connect.......")
sleep(10)
print("FAILED.....Retrying.....")
sleep(10)
print("FAILED.....Retrying.....")
sleep(10)
print("FAILED.....Retrying.....")
sleep(3)
print("Got Access!")
sleep(1)
print("Uploading Contents To your computer........")
sleep(20)
print("Hacked succesfullty")
print("congratulation.....")
sleep(2)
print("for waisting your time!")